#!/usr/bin/env node

import { createHash } from 'node:crypto'
import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

import { assert, isObject, readCategories, sourceUrl } from './lib/catalog-entry.mjs'

const scriptRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
export const defaultBase = 'https://deepseek1024.com'
// Must stay aligned with UNCLASSIFIED_CATEGORY in apps/web/worker/lib/categories.ts
// (the website/API label for the same bucket); the .mjs script cannot import Worker TS.
const unclassifiedLabel = { en: 'Unclassified', zh: '待分类' }
const generatedNotice = {
  zh: '<!-- 本文件由 scripts/build-readme.mjs 从 deepseek1024.com 目录 API 自动生成，请勿手工编辑。 -->',
  en: '> This file is generated by `scripts/build-readme.mjs` from the DSH 1024Store catalog API. Do not edit it directly.',
}

function text(value) {
  return typeof value === 'string' ? value.replace(/\s+/g, ' ').trim() : ''
}

function updatedDate(value) {
  const date = typeof value === 'string' ? value.slice(0, 10) : ''
  assert(/^\d{4}-\d{2}-\d{2}$/.test(date), `Registry has an invalid updated timestamp: ${String(value)}`)
  return date
}

function normalizePlugin(plugin, id, stars) {
  assert(isObject(plugin), 'Registry contains an invalid plugin entry')
  const name = text(plugin.name)
  const url = typeof plugin.url === 'string' ? plugin.url : ''
  assert(name.length > 0 && /^https:\/\/github\.com\//.test(url), `Registry plugin ${id} must have a name and GitHub url`)
  return {
    id,
    name,
    owner: text(plugin.owner),
    url,
    category: typeof plugin.category === 'string' && plugin.category.length > 0 ? plugin.category : 'unclassified',
    description: {
      en: text(plugin.description?.en),
      zh: text(plugin.description?.zh),
    },
    added: typeof plugin.added === 'string' ? plugin.added : null,
    stars,
  }
}

export function normalizeRegistry(data) {
  assert(isObject(data) && Array.isArray(data.plugins), 'Registry response must contain a plugins array')
  // A capped /api/v1/registry response advertises the full catalog size in
  // `total` while serving only its install-ranked head. Regenerating from it —
  // over the network or via --from-file — would silently shrink the README to
  // the cap, so it is refused here, in the one place every registry-shaped
  // payload passes through.
  assert(
    typeof data.total !== 'number' || data.total <= data.plugins.length,
    'The registry payload is capped and cannot rebuild the README; use a full-catalog source such as /api/v2/plugins',
  )
  return {
    updated: updatedDate(data.updated),
    plugins: data.plugins.map(plugin => {
      assert(isObject(plugin) && typeof plugin.id === 'string' && /^[^/]+\/[^/]+(\/[^/]+)*$/.test(plugin.id), 'Registry plugins must carry an owner/repository[/sub/dir] id')
      return normalizePlugin(plugin, plugin.id, Number.isInteger(plugin.stars) ? plugin.stars : null)
    }),
  }
}

export function adaptLegacyRegistry(data) {
  assert(isObject(data) && Array.isArray(data.plugins), 'Legacy /plugins.json must contain a plugins array')
  return {
    updated: updatedDate(data.updated),
    plugins: data.plugins.map(plugin => {
      assert(isObject(plugin) && typeof plugin.url === 'string', 'Legacy plugins must carry a url')
      const derived = new URL(plugin.url).pathname.replace(/^\/+/, '').replace(/\/+$/, '')
      const id = /^[^/]+\/[^/]+$/.test(derived) ? derived : `${plugin.owner}/${plugin.name}`
      return normalizePlugin(plugin, id, null)
    }),
  }
}

function detectRegistryShape(data) {
  const plugins = isObject(data) ? data.plugins : undefined
  const first = Array.isArray(plugins) ? plugins.find(value => isObject(value)) : undefined
  if (first !== undefined && typeof first.id !== 'string') return adaptLegacyRegistry(data)
  return normalizeRegistry(data)
}

const v2PageLimit = 200
// One sort per attempt. Membership does not depend on the sort, but the edge
// cache keys on it, so a retry under a different real sort value reads fresh
// origin pages instead of replaying whichever mixed cached copies just failed
// the consistency check. (The edge cache deliberately strips unknown params,
// so a synthetic cache-buster would not work.)
const v2SweepSorts = ['name', 'active', 'newest']
const v2SweepRetryDelayMs = 10_000

function v2PageUrl(base, sort, page) {
  return `${base}/api/v2/plugins?sort=${sort}&limit=${v2PageLimit}&page=${page}`
}

// The README needs the whole catalog, and /api/v1/registry no longer serves it
// (the endpoint caps at its install-ranked head), so the projections page
// through /api/v2/plugins instead. A page sweep is not atomic — the 15-minute
// KV snapshot can rotate mid-sweep, the edge can hold pages cached from
// different snapshots, and a single page can hit a transient 5xx — so a sweep
// only counts when every page arrives, reports the same generatedAt, and the
// pages add up to the advertised total; anything else retries under the next
// sort, and a persistent failure fails the build rather than publishing a
// partial listing.
async function loadPagedCatalog(fetchImplementation, base, retryDelayMs = v2SweepRetryDelayMs) {
  let lastError = null
  for (const [attempt, sort] of v2SweepSorts.entries()) {
    if (attempt > 0 && retryDelayMs > 0) {
      await new Promise(resolve => setTimeout(resolve, retryDelayMs))
    }
    const firstResponse = await fetchImplementation(v2PageUrl(base, sort, 1))
    if (firstResponse.status === 404) return null
    if (!firstResponse.ok) {
      lastError = new Error(`GET ${base}/api/v2/plugins failed: HTTP ${firstResponse.status}`)
      continue
    }
    const first = JSON.parse(await firstResponse.text())
    assert(
      isObject(first) && Array.isArray(first.plugins)
        && Number.isInteger(first.totalPages) && first.totalPages >= 1
        && Number.isInteger(first.total) && typeof first.generatedAt === 'string',
      'The /api/v2/plugins response is missing its pagination metadata',
    )
    const plugins = [...first.plugins]
    let attemptError = null
    for (let page = 2; page <= first.totalPages; page += 1) {
      const response = await fetchImplementation(v2PageUrl(base, sort, page))
      if (!response.ok) {
        attemptError = new Error(`GET ${base}/api/v2/plugins page ${page} failed: HTTP ${response.status}`)
        break
      }
      const body = JSON.parse(await response.text())
      if (!isObject(body) || !Array.isArray(body.plugins) || body.generatedAt !== first.generatedAt) {
        attemptError = new Error('The catalog snapshot rotated while paging /api/v2/plugins; the sweep was inconsistent')
        break
      }
      plugins.push(...body.plugins)
    }
    if (attemptError === null) {
      const ids = new Set(plugins.map(plugin => (isObject(plugin) ? plugin.id : undefined)))
      if (plugins.length === first.total && ids.size === plugins.length) {
        return normalizeRegistry({ updated: first.generatedAt, plugins })
      }
      attemptError = new Error('The /api/v2/plugins sweep did not add up to the advertised catalog total')
    }
    lastError = attemptError
  }
  throw lastError
}

export async function loadRegistry(options = {}) {
  if (options.fromFile !== undefined) {
    return detectRegistryShape(JSON.parse(await readFile(options.fromFile, 'utf8')))
  }
  const fetchImplementation = options.fetchImplementation ?? globalThis.fetch
  const base = (options.base ?? defaultBase).replace(/\/+$/, '')
  const paged = await loadPagedCatalog(fetchImplementation, base, options.retryDelayMs)
  if (paged !== null) return paged
  // v2 not deployed yet: the original bootstrap chain. normalizeRegistry
  // refuses a capped registry response (total larger than the entries served)
  // instead of silently shrinking the README to the cap.
  const registryResponse = await fetchImplementation(`${base}/api/v1/registry`)
  if (registryResponse.ok) {
    return normalizeRegistry(JSON.parse(await registryResponse.text()))
  }
  if (registryResponse.status !== 404) {
    throw new Error(`GET ${base}/api/v1/registry failed: HTTP ${registryResponse.status}`)
  }
  const legacyResponse = await fetchImplementation(`${base}/plugins.json`)
  if (!legacyResponse.ok) {
    throw new Error(`GET ${base}/plugins.json fallback failed: HTTP ${legacyResponse.status}`)
  }
  return adaptLegacyRegistry(JSON.parse(await legacyResponse.text()))
}

function comparePlugins(left, right) {
  const leftName = left.name.toLocaleLowerCase('en-US')
  const rightName = right.name.toLocaleLowerCase('en-US')
  return leftName.localeCompare(rightName, 'en-US')
    || left.name.localeCompare(right.name, 'en-US')
    || left.id.localeCompare(right.id, 'en-US')
}

export function groupPlugins(registry, categories) {
  const ordered = [...categories].sort((left, right) => (left.order ?? 0) - (right.order ?? 0) || String(left.id).localeCompare(String(right.id), 'en-US'))
  const buckets = new Map(ordered.map(category => [category.id, []]))
  const unclassified = []
  for (const plugin of registry.plugins) {
    (buckets.get(plugin.category) ?? unclassified).push(plugin)
  }
  const groups = ordered
    .filter(category => buckets.get(category.id).length > 0)
    .map(category => ({
      id: category.id,
      label: category.label,
      plugins: [...buckets.get(category.id)].sort(comparePlugins),
    }))
  if (unclassified.length > 0) {
    groups.push({ id: 'unclassified', label: unclassifiedLabel, plugins: [...unclassified].sort(comparePlugins) })
  }
  return groups
}

function pluginLine(plugin, locale) {
  const preferred = plugin.description[locale]
  const fallback = locale === 'zh' ? plugin.description.en : plugin.description.zh
  const description = preferred.length > 0 ? preferred : fallback
  // The plugin's own directory, not its repository: a monorepo contributes one
  // line per package, and pointing them all at the repository root would make
  // every line but the first a dead end for the reader.
  const href = sourceUrl(plugin.id)
  return description.length > 0
    ? `- [${plugin.name}](${href}) — ${description}`
    : `- [${plugin.name}](${href})`
}

// The homepage screenshot lives on a dedicated orphan `assets` branch that CI
// force-pushes to a single commit, so republishing it never grows the repository.
// GitHub proxies README images through camo and keys that cache on the URL, so a
// stable URL would leave readers looking at a stale screenshot. The cache-buster is
// derived from the catalog contents rather than the clock: the image URL changes
// exactly when the plugin list changes, which keeps the screenshot in step with the
// list without producing a README commit on every no-op sync.
export const screenshotBranch = 'assets'
// One capture per language: the site picks its locale from navigator.language, so each
// projection shows the store in the language its readers are reading.
export const screenshotPaths = { zh: 'homepage.zh.png', en: 'homepage.en.png' }
const screenshotRepository = 'imsai-sh/awesome-deepseek-harness-plugins'

export function catalogRevision(registry) {
  const material = registry.plugins.map(plugin => `${plugin.id}\u0000${plugin.category}`).join('\n')
  return createHash('sha256').update(`${registry.updated}\n${material}`).digest('hex').slice(0, 12)
}

function heroImage(registry, locale) {
  const alt = locale === 'zh' ? 'DSH 1024Store 插件市场首页' : 'The DSH 1024Store plugin marketplace homepage'
  const source = `https://raw.githubusercontent.com/${screenshotRepository}/${screenshotBranch}/${screenshotPaths[locale]}?v=${catalogRevision(registry)}`
  return `[![${alt}](${source})](https://deepseek1024.com/)`
}

function communityQr() {
  return `<div align="center">
  <strong>DSH插件社区</strong><br><br>
  <img src="apps/web/public/wechat-group.jpg" alt="DSH插件社区微信二维码" width="280">
</div>`
}

// GitHub stops rendering Markdown at 500 KiB and gives no truncation notice: every
// entry past that byte offset simply does not exist for readers. Measured against the
// live catalog on 2026-08-16, an uncapped projection was 594 KB and silently dropped
// its last 479 plugins.
//
// The cap is a byte budget, not an entry count, because an entry costs whatever its
// rendered line costs and that cost moves under us. A fixed 500-entry cap on the
// auto-discovered `unclassified` bucket held only while that bucket was the sole one
// big enough to matter and its lines were short. The classification pass ended both
// conditions in one go: it gave every entry a bilingual description (roughly doubling
// the average line) and emptied `unclassified` into the curated categories, so a cap
// keyed to a bucket and counted in entries had nothing left to trim and reported no
// truncation while the projection sailed 210 KB past the limit. Any entry count that
// fits today is a silent truncation the next time descriptions grow, so the budget is
// measured in the only unit GitHub actually enforces.
//
// Both projections are budgeted separately: the same entry costs about three bytes per
// Chinese character in README.md against one per ASCII character in catalog/README.md,
// and the two descriptions are written independently, so one shared entry count would
// truncate one file needlessly while overshooting the other. Each locale is fitted in
// two passes — render the whole file with every list emptied to price what is not the
// lists themselves (prose, index, summaries, truncation notices), then split what is
// left between the groups.
//
// That split is max-min fair (see `fairShares`) rather than first-come: a category that
// needs less than an equal share is listed in full and releases the surplus, so only
// the genuinely oversized categories are cut, and never so that an earlier one can be
// whole at a later one's expense. Curated categories are served first and `unclassified`
// takes the leftover, which reproduces the old rule exactly whenever the curated set
// fits: full curated lists, `unclassified` capped.
//
// Every pass reads sorted arrays and integer byte counts, so the same input always
// yields the same output: no clock, no Map iteration order, no hashing. Each list keeps
// its natural (name) ordering — `added` carries no usable ordering signal here, since
// the topic-scan backfill gave most of the catalog the same date.
export const githubRenderLimit = 500 * 1024
// Headroom below the hard limit. The fitted lists land just under `limit - margin`; the
// margin absorbs the few bytes the counts in each summary and truncation notice gain as
// the lists fill, and leaves room for GitHub to be stricter than we measure.
const renderSafetyMargin = 8 * 1024

// An entry costs its rendered bytes plus the newline that joins it to the list.
function entryCost(plugin, locale) {
  return Buffer.byteLength(pluginLine(plugin, locale), 'utf8') + 1
}

function listCost(group, locale) {
  return group.plugins.reduce((total, plugin) => total + entryCost(plugin, locale), 0)
}

function withVisiblePlugins(group, locale, budget) {
  const visible = []
  let spent = 0
  for (const plugin of group.plugins) {
    const cost = entryCost(plugin, locale)
    if (spent + cost > budget) break
    spent += cost
    visible.push(plugin)
  }
  return { ...group, total: group.plugins.length, visible, capped: visible.length < group.plugins.length }
}

// Max-min fair split of `budget` over the given list costs: every group may spend an
// equal share, a group that needs less than its share takes only what it needs and
// releases the surplus, and the round repeats until no group is newly satisfied. Small
// categories are therefore never truncated to make room for a large one. Returns the
// per-group allowance in input order plus whatever is still unspent.
function fairShares(costs, budget) {
  const shares = costs.map(() => 0)
  let open = costs.map((_, index) => index)
  let remaining = budget
  while (open.length > 0) {
    const share = Math.floor(remaining / open.length)
    const satisfied = open.filter(index => costs[index] <= share)
    if (satisfied.length === 0) {
      for (const index of open) shares[index] = share
      remaining -= share * open.length
      break
    }
    for (const index of satisfied) {
      shares[index] = costs[index]
      remaining -= costs[index]
    }
    open = open.filter(index => costs[index] > share)
  }
  return { shares, remaining }
}

// Pass one prices the projection with every list emptied: a zero budget still renders
// each summary and truncation notice, so the measurement covers every byte the finished
// file spends outside the lists. Whatever is left under the limit is what pass two may
// spend on entries.
function fitGroups(registry, groups, locale) {
  const emptied = groups.map(group => withVisiblePlugins(group, locale, 0))
  const overhead = Buffer.byteLength(renderReadme(registry, groups, emptied, locale), 'utf8')
  const budget = Math.max(githubRenderLimit - renderSafetyMargin - overhead, 0)
  const curated = groups.map((group, index) => index).filter(index => groups[index].id !== 'unclassified')
  const { shares, remaining } = fairShares(curated.map(index => listCost(groups[index], locale)), budget)
  // Anything outside the curated set — in practice only `unclassified` — is served last,
  // out of what the curated categories left behind.
  const budgets = groups.map(() => remaining)
  curated.forEach((groupIndex, shareIndex) => { budgets[groupIndex] = shares[shareIndex] })
  return groups.map((group, index) => withVisiblePlugins(group, locale, budgets[index]))
}

export function assertRenderable(files) {
  for (const [relative, content] of Object.entries(files)) {
    const bytes = Buffer.byteLength(content, 'utf8')
    assert(
      bytes <= githubRenderLimit,
      `${relative} is ${bytes} bytes; GitHub renders at most ${githubRenderLimit} and silently drops everything past that offset. The plugin lists are already fitted to a byte budget, so this means everything around them — prose, the category index, the per-category summaries — no longer fits: trim that copy or raise renderSafetyMargin in scripts/build-readme.mjs.`,
    )
  }
}

function escapeHtml(value) {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

function categoryIndex(groups, locale) {
  return groups.map(group => `- [${group.label[locale]}](#${group.id}) (${group.plugins.length})`).join('\n')
}

// Each category is a collapsed <details> block: the full list is ~3k entries, so an
// expanded README buries everything above it. GitHub only renders Markdown inside
// <details> when the element is unindented and the <summary> is followed by a blank
// line, and category labels contain "&", so the summary text must be HTML-escaped.
// The <a id> anchor stays outside the block so the category index still jumps to a
// collapsed group.
function categorySections(prepared, locale) {
  return prepared.map(group => {
    const count = group.capped
      ? (locale === 'zh' ? `显示 ${group.visible.length} / 共 ${group.total} 个` : `showing ${group.visible.length} of ${group.total}`)
      : (locale === 'zh' ? `${group.total} 个插件` : `${group.total} plugins`)
    const lines = group.visible.map(plugin => pluginLine(plugin, locale))
    if (group.capped) {
      const rest = group.total - group.visible.length
      lines.push(locale === 'zh'
        ? `- *GitHub 单个文件能渲染的长度有上限，本分类还有 ${rest} 个插件没能列在这里；完整目录请在[在线网站](https://deepseek1024.com/)搜索浏览。*`
        : `- *GitHub only renders so much of one file, so ${rest} more plugins in this category did not fit here — search or browse the full catalog on the [live website](https://deepseek1024.com/).*`)
    }
    return [
      `<a id="${group.id}"></a>`,
      '',
      '<details>',
      `<summary><strong>${escapeHtml(group.label[locale])}</strong> · ${count}</summary>`,
      '',
      lines.join('\n'),
      '',
      '</details>',
    ].join('\n')
  }).join('\n\n')
}

function chineseReadme(registry, groups, prepared) {
  const total = registry.plugins.length
  return `# DSH 1024Store

${generatedNotice.zh}

面向 [DeepSeek Harness](https://github.com/deepseek-ai/DeepSeek-Harness)（\`dsh\`）生态的社区插件目录，共收录 **${total}** 个插件（含 PR 收录与 GitHub \`dsh-plugin\` topic 自动发现），目录数据更新于 ${registry.updated}。

**但这个仓库不只是一份 awesome list。** 这里开源了一个在线插件市场、一个把市场装进 \`dsh\` 本体的插件、经静态校验的 PR 收录流水线，以及一套免费的公开查询 API；目录数据另有自动收集服务持续喂入。代码采用 MIT 协议，fork 之后就能部署成你自己的插件市场。

${heroImage(registry, 'zh')}

[在线网站](https://deepseek1024.com/) · [API 文档](docs/api.md) · [英文目录](catalog/README.md) · [提交插件](CONTRIBUTING.md)

[![GitHub Stars](https://img.shields.io/github/stars/imsai-sh/awesome-deepseek-harness-plugins?style=social)](https://github.com/imsai-sh/awesome-deepseek-harness-plugins/stargazers)

${communityQr()}

## 项目亮点

### 在线插件市场（开源 · 可一键自部署）

[deepseek1024.com](https://deepseek1024.com/) 提供搜索、分类筛选、安装排行榜、插件详情与 GitHub 活跃度数据。整站跑在 Cloudflare Workers + D1 + KV 上，源码在 [\`apps/web\`](apps/web)。

想要一个完全属于自己的插件市场：fork 本仓库，把 \`apps/web/wrangler.jsonc\` 里的 \`routes\` 换成你自己的域名，创建 D1 数据库与 KV 命名空间，配齐 \`secrets.required\` 列出的 Worker secret，再把 \`CLOUDFLARE_API_TOKEN\` 与 \`CLOUDFLARE_ACCOUNT_ID\` 存为仓库 secret。配置完成后，每次 push 到 \`main\` 都由 GitHub Actions 自动执行 D1 迁移并部署 Worker，不需要自己写一行部署脚本。完整步骤见下文[本地运行与部署](#本地运行与部署)。

### 把插件市场装进 dsh 本体

不想切浏览器，就把市场本身作为插件装进 DeepSeek Harness：

\`\`\`bash
dsh plugin --profile web add dsh1024@latest
\`\`\`

重启后「设置」里会出现独立的 **1024 Store** 入口，「设置 → 插件」下也会多出一个 **1024 Store（数量）** 标签页，可以直接搜索目录、按分类筛选、识别已安装状态、安装与卸载，并显示操作进度。安装器只接受目录 API 返回并通过严格语法校验的结构化目标：优先使用已发布 npm 包，否则使用与插件 ID、仓库 URL 一致的 GitHub 源码规格；展示命令不会被直接执行。源码见 [\`packages/dsh1024\`](packages/dsh1024)。

### 定时自动收集 + 格式校验

这是本目录与多数插件市场最大的区别：**目录不靠人肉维护，收录前一定过校验。**

- **定时收集**：自动收录带 \`dsh-plugin\` topic 的 GitHub 仓库，增量抓取新建与新推送的仓库，并定期全量对账——长期不活跃的仓库不会被漏收，掉了 topic 也只在一次成功的全量对账后才下架。
- **格式校验**：每个候选仓库都要通过静态校验——读取默认分支的 Git tree，检查 \`package.json\`、\`dsh.bundle.patch\` 字段，以及 patch 文件在同一棵 tree 中确实存在。**全程只读文件，绝不安装依赖、绝不执行仓库代码。** 校验不通过就不进目录。
- **自动同步**：PR 合并后由 CI 自动同步目录到网站数据库并刷新本 README，贡献者和维护者都不需要手工改任何生成文件。

数据来源与校验语义见 [目录数据来源文档](docs/plugin-discovery.md)。

### 免费查询 API

目录数据免费开放，匿名即可调用：

\`\`\`bash
curl 'https://api.deepseek1024.com/v1/plugins/search?q=memory'
\`\`\`

匿名调用每天 50 次、每分钟 10 次；用 GitHub 账号登录网站创建 API Key 后提升到每天 500 次、每分钟 30 次。另有 \`/api/v1/registry\` 返回按安装热度排序的精简目录快照（至多 500 条）。完整端点、参数与错误码见 [API 参考](docs/api.md)。

## 参与进来

这个项目由社区维护，下面每一种参与都真的有用：

- **点个 Star** — [Star 本仓库](https://github.com/imsai-sh/awesome-deepseek-harness-plugins/stargazers)是成本最低、帮助最大的支持，能让更多 DeepSeek Harness 用户找到这里。
- **提 Issue** — 插件信息有误、分类不合理、网站或 API 有问题、想要新功能，都欢迎[提 Issue](https://github.com/imsai-sh/awesome-deepseek-harness-plugins/issues/new)。
- **发 PR** — [提交你自己的插件](CONTRIBUTING.md)，或改进网站、CLI、市场插件与目录流水线，欢迎直接发 [Pull Request](https://github.com/imsai-sh/awesome-deepseek-harness-plugins/pulls)。
- **Fork 自建** — 想要自己的插件市场，[Fork](https://github.com/imsai-sh/awesome-deepseek-harness-plugins/fork) 之后按上面的步骤配置即可，MIT 协议，随便改。

## 安装插件并计入统计

1024 Store 只提供 npm 安装：插件详情页展示的命令安装的是作者发布到 npm、声明 \`dsh.bundle\` 的包；尚未发布 npm 包的插件以浏览模式收录（有仓库链接，无安装命令）。网站优先提供开源包装 CLI；它会调用官方 DeepSeek Harness 插件命令、校验 profile 的真实安装结果，并把匿名安装结果可靠地上报到排行榜：

\`\`\`bash
dsh1024 plugin --profile web add <npm-package>
\`\`\`

首次使用先一次性全局安装：\`npm install -g dsh1024\`。它与官方命令只差一个名字——\`plugin\` 之后的参数原样转发给官方 CLI，不增删、不改写、不重排，包装器只负责在结束后核对 profile 并记录一条匿名安装结果。参数不会写入遥测或本地 receipt。

monorepo 子目录插件的标识形如 \`owner/repo/packages/foo\`，每个子包发布并安装自己的 npm 包，同仓库的兄弟插件各自独立计数。

统计身份是保存在 \`$DSH_HOME/.dsh-1024store/\` 的随机安装实例 ID，不是实名用户或账号。CLI 不上传命令输出、路径、用户名、环境变量、会话内容或原始错误；可用 \`npx dsh1024 telemetry disable\`、\`DO_NOT_TRACK=1\` 或 \`DSH1024_TELEMETRY=0\`（旧变量名 \`DSH_1024STORE_TELEMETRY\` 仍兼容）关闭。直接使用官方 \`dsh plugin\` 命令仍然可用，但不会计入 DSH 1024Store 安装统计。详细字段、口径、存储和部署方式见 [安装统计设计](docs/install-analytics.md)，CLI 源码见 [\`packages/dsh1024\`](packages/dsh1024)。

## 提交插件

### 使用 Agent Skill 提交（推荐）

如果你使用 Codex、Claude Code、Cursor 或其他兼容 Agent Skills 的编程助手，可以安装本仓库提供的提交 Skill：

\`\`\`bash
npx skills add imsai-sh/awesome-deepseek-harness-plugins --skill submit-dsh-plugin -g
\`\`\`

安装后告诉助手：

\`\`\`text
使用 $submit-dsh-plugin 检查并提交我的 DeepSeek Harness 插件。
\`\`\`

该 Skill 会检查插件仓库、生成唯一允许提交的目录 JSON、验证变更范围，并在获得授权后创建 PR。新增条目的非草稿 PR 通过静态审查后会自动合并；修改或删除既有条目的 PR 同样会跑静态审查，但不会自动合并，需要维护者人工审核后手动合并。合并后 CI 自动同步目录到网站数据库并刷新本 README，贡献者和维护者都不需要手工更新任何生成文件。查看 [Skill 源码](skills/submit-dsh-plugin/SKILL.md)。

### 手动提交

欢迎把你的 DeepSeek Harness 插件提交到本目录。请阅读 [CONTRIBUTING.md](CONTRIBUTING.md)，通过 PR 提交一个新的结构化插件文件；自动审查将验证提交范围和最基础的 DeepSeek Harness 插件配置，通过后自动合并，并由 CI 自动同步到网站与本 README。需要修正或下架既有条目时也可以发 PR，静态审查照常运行，但这类 PR 由维护者人工审核后合并。

安装命令以插件详情页展示的 npm 包为准：\`dsh1024 plugin --profile web add <npm-package>\`（首次使用先 \`npm install -g dsh1024\`）。

## 项目定位

本项目与 [awesome-dsh-plugin](https://github.com/awesome-dsh-plugin/awesome-dsh-plugin) 都服务于 DeepSeek Harness 插件生态。在继承其目录数据与社区整理思路的基础上，本项目把「一份人工维护的列表」扩展成一套开源、可自部署的插件市场基建：在线市场网站、dsh 内置市场插件、静态校验的 PR 收录流水线与免费查询 API，并由自动收集服务持续补充目录数据，具体见上文[项目亮点](#项目亮点)。

## 项目结构

\`\`\`text
catalog/plugins/    插件提交表单与 curated 元数据（每个插件一个 JSON）
catalog/categories.json  分类定义（唯一分类信源）
skills/             面向贡献者的可安装 Agent Skills
apps/web/src/       React + Vite 前端
apps/web/worker/    Cloudflare Worker API 与数据刷新
packages/dsh1024/   dsh1024 npm 包：上报安装统计的包装 CLI + DSH 设置页内插件市场
scripts/            提交审查、目录同步与 README 生成脚本
\`\`\`

线上目录数据的唯一信源是 Cloudflare D1；本 README 与 [catalog/README.md](catalog/README.md) 由 CI 从目录 API 全量生成，职责划分见 [仓库布局](docs/repository-layout.md)。

## 本地运行与部署

需要 Node.js 22+、npm 10+。本地开发：

\`\`\`bash
npm ci
cd apps/web
npx wrangler d1 migrations apply dsh-store-star-history --local
cd ../..
npm run dev
\`\`\`

浏览器访问 <http://127.0.0.1:5173>。如需完整 GitHub 数据，可在 \`apps/web/.dev.vars\` 中配置 \`GITHUB_TOKEN\`；本地接收安装事件还需要一个至少 32 字符的 \`INSTALL_CLIENT_HASH_SECRET\`。

部署到 Cloudflare Workers：

\`\`\`bash
cp apps/web/.env.example apps/web/.dev.vars
# 在 apps/web/.dev.vars 中填写 GITHUB_TOKEN 和 INSTALL_CLIENT_HASH_SECRET
npx wrangler login
npm run build
cd apps/web
npx wrangler d1 migrations apply dsh-store-star-history --remote
npx wrangler deploy --secrets-file .dev.vars
\`\`\`

\`wrangler.jsonc\` 已声明 KV、D1、Durable Object 和静态资源配置。生产环境要先执行 \`npm run db:migrate:remote\`，再部署 Worker；完整顺序见 [目录数据来源文档](docs/plugin-discovery.md)，公开 API 见 [API 参考](docs/api.md)。请勿提交 \`.dev.vars\`。

## 致谢

感谢以下项目为本目录提供基础与参考：

- [DeepSeek Harness](https://github.com/deepseek-ai/deepseek-harness)：提供插件系统、\`dsh.bundle\` 规范和插件开发文档。
- [awesome-dsh-plugin](https://github.com/awesome-dsh-plugin/awesome-dsh-plugin)：提供初始插件目录数据和社区目录设计参考。

## 插件分类

分组默认折叠，点开即可展开。GitHub 对单个文件的渲染长度有上限，条目较多的分类只列出其中一部分（分类标题会写明列出了多少），完整目录请在[在线网站](https://deepseek1024.com/)搜索浏览。

${categoryIndex(groups, 'zh')}

${categorySections(prepared, 'zh')}

## 免责声明

本项目是社区维护的插件索引。插件由各自作者开发和维护，收录不构成安全、质量或维护状态背书。安装插件会在本机运行第三方代码，请在安装前自行审阅源码和依赖。

## 许可证

本仓库采用分区许可：

- 应用、自动化与构建工具等源代码采用 [MIT License](LICENSE)。
- \`catalog/\` 下的插件目录元数据采用 [CC0-1.0](catalog/LICENSE)。
- 初始目录数据导入自 \`awesome-dsh-plugin\`，来源和导入提交见 [catalog/ATTRIBUTION.md](catalog/ATTRIBUTION.md)。

目录中列出的第三方插件不属于本仓库，其源代码分别遵循各自仓库的许可证。
`
}

function englishReadme(registry, groups, prepared) {
  const total = registry.plugins.length
  return `# Awesome DeepSeek Harness Plugins

${generatedNotice.en}

The **DSH 1024Store** community catalog for [DeepSeek Harness](https://github.com/deepseek-ai/DeepSeek-Harness) plugins: **${total}** plugins, updated ${registry.updated}.

**This repository is more than an awesome list.** It open-sources a hosted plugin marketplace, a plugin that puts that marketplace inside \`dsh\` itself, a statically validated PR submission pipeline, and a free public query API; an automated collection service feeds the catalog alongside them. The code is MIT licensed, so you can fork it and run your own marketplace.

${heroImage(registry, 'en')}

[Live website](https://deepseek1024.com/) · [API reference](../docs/api.md) · [中文目录](../README.md) · [Submit a plugin](../CONTRIBUTING.md)

[![GitHub Stars](https://img.shields.io/github/stars/imsai-sh/awesome-deepseek-harness-plugins?style=social)](https://github.com/imsai-sh/awesome-deepseek-harness-plugins/stargazers)

## What this repository ships

- **Hosted plugin marketplace, one fork away.** [deepseek1024.com](https://deepseek1024.com/) offers search, category filters, install rankings, plugin detail pages, and GitHub activity data on Cloudflare Workers + D1 + KV ([\`apps/web\`](../apps/web)). To self-host: fork the repository, point \`routes\` in \`apps/web/wrangler.jsonc\` at your own domain, create the D1 database and KV namespace, set the Worker secrets listed under \`secrets.required\`, and add \`CLOUDFLARE_API_TOKEN\` and \`CLOUDFLARE_ACCOUNT_ID\` as repository secrets. From then on every push to \`main\` runs the D1 migrations and deploys the Worker for you.
- **The marketplace as a \`dsh\` plugin.** \`dsh plugin --profile web add dsh1024@latest\` installs or upgrades a **1024 Store** entry in Settings and a **1024 Store (count)** tab under Settings → Plugins, with search, filters, installed-state detection, install, and uninstall ([\`packages/dsh1024\`](../packages/dsh1024)).
- **Scheduled collection with format validation.** GitHub repositories carrying the \`dsh-plugin\` topic are collected automatically and periodically reconciled against the full set. Every candidate is statically validated — the default-branch Git tree, \`package.json\`, \`dsh.bundle.patch\`, and the patch blob must exist — by reading files only, never installing dependencies or executing repository code ([\`docs/plugin-discovery.md\`](../docs/plugin-discovery.md)).
- **Free query API.** \`curl 'https://api.deepseek1024.com/v1/plugins/search?q=memory'\` works anonymously at 50 requests/day (10/minute); a GitHub-login API key raises that to 500/day (30/minute). \`/api/v1/registry\` serves a compact, install-ranked snapshot of the catalog (at most 500 entries) — see [\`docs/api.md\`](../docs/api.md).

## Get involved

- **Star** the [repository](https://github.com/imsai-sh/awesome-deepseek-harness-plugins/stargazers) so more DeepSeek Harness users find the catalog.
- **Open an [issue](https://github.com/imsai-sh/awesome-deepseek-harness-plugins/issues/new)** for wrong plugin metadata, a bad category, or a website/API bug.
- **Send a [pull request](https://github.com/imsai-sh/awesome-deepseek-harness-plugins/pulls)** — [submit your plugin](../CONTRIBUTING.md) or improve the website, CLI, marketplace plugin, or catalog pipeline.
- **[Fork](https://github.com/imsai-sh/awesome-deepseek-harness-plugins/fork)** it and run your own marketplace — see the self-hosting steps above.

The 1024 Store installs plugins from npm only: each plugin's detail page shows the command for its published npm package, and a plugin without one is listed browse-only with its repository link. Install any published plugin and count it on the leaderboard with:

\`\`\`bash
npm install -g dsh1024   # once
dsh1024 plugin --profile web add <npm-package>
\`\`\`

Monorepo subpackage plugins publish and install their own npm packages, and each sibling is counted on its own. A pull request that adds one new entry is merged automatically once static review passes; one that updates or removes an existing entry passes the same review but waits for maintainer approval. Merged submissions are synced to the website database and into this file automatically; no manual list editing is involved.

## Categories

Groups are collapsed by default. GitHub renders only so much of a single file, so the largest categories list a subset — each summary says how many — while smaller ones are complete. Search the [live website](https://deepseek1024.com/) for the full catalog.

${categoryIndex(groups, 'en')}

${categorySections(prepared, 'en')}
`
}

function renderReadme(registry, groups, prepared, locale) {
  return locale === 'zh' ? chineseReadme(registry, groups, prepared) : englishReadme(registry, groups, prepared)
}

export async function buildReadmeFiles(registry, categories) {
  const groups = groupPlugins(registry, categories)
  const files = {}
  for (const [locale, relative] of [['zh', 'README.md'], ['en', 'catalog/README.md']]) {
    files[relative] = renderReadme(registry, groups, fitGroups(registry, groups, locale), locale)
  }
  assertRenderable(files)
  return files
}

export function parseArguments(argv) {
  const options = { root: scriptRoot, base: defaultBase, check: false, help: false }
  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index]
    const value = () => {
      const next = argv[index + 1]
      if (next === undefined || next.startsWith('--')) throw new Error(`${argument} requires a value`)
      index += 1
      return next
    }
    if (argument === '--base') options.base = value()
    else if (argument === '--from-file') options.fromFile = path.resolve(value())
    else if (argument === '--root') options.root = path.resolve(value())
    else if (argument === '--check') options.check = true
    else if (argument === '--help' || argument === '-h') options.help = true
    else throw new Error(`Unknown argument: ${argument}`)
  }
  return options
}

function usage() {
  return `Usage: npm run readme:build [-- options]

Regenerates README.md (Chinese) and catalog/README.md (English) from the full
DSH 1024Store catalog: paged GET <base>/api/v2/plugins sweeps, falling back to
the uncapped-era <base>/api/v1/registry and then the legacy <base>/plugins.json
shape when newer endpoints are not deployed yet.

Options:
  --base <url>        Catalog API origin (default: ${defaultBase})
  --from-file <json>  Build from a local registry JSON file instead of the network
  --root <path>       Repository root for categories.json and output files
  --check             Verify the committed files are current; do not write
  --help              Show this help`
}

async function main() {
  const options = parseArguments(process.argv.slice(2))
  if (options.help) {
    console.log(usage())
    return
  }
  const categories = await readCategories(options.root)
  const registry = await loadRegistry(options)
  assert(
    registry.plugins.length > 0,
    'Registry returned 0 plugins; refusing to regenerate README projections from a degenerate snapshot.',
  )
  const files = await buildReadmeFiles(registry, categories)

  if (options.check) {
    const stale = []
    for (const [relative, content] of Object.entries(files)) {
      const existing = await readFile(path.join(options.root, relative), 'utf8').catch(() => '')
      if (existing !== content) stale.push(relative)
    }
    if (stale.length > 0) {
      console.error(`Stale generated files: ${stale.join(', ')}. Run npm run readme:build.`)
      process.exitCode = 1
      return
    }
    console.log('README projections are up to date.')
    return
  }

  for (const [relative, content] of Object.entries(files)) {
    await writeFile(path.join(options.root, relative), content)
    console.log(`Wrote ${relative} (${registry.plugins.length} plugins, updated ${registry.updated})`)
  }
}

if (process.argv[1] !== undefined && pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url) {
  try {
    await main()
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error))
    process.exitCode = 1
  }
}
